[application]
name = "saturn-aggregator"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Saturn Aggregator"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
